feat: http error handling without retries
adobe/aem-genai-assistant pull request #226
Opened 2024-03-14 08:21 UTC by vtsaplin

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-03-14 12:47 UTC, basecode approved these changes
LGTM

2024-03-14 12:47 UTC, basecode commented on actions/AuthAction.js
> +    const { valid } = response;
`return response.valid`?

2024-03-15 09:40 UTC, askayastha22 commented on web-src/src/helpers/NetworkHelper.js
> +      return _
I would have preferred a parameter name such as `request`.

2024-03-15 09:42 UTC, askayastha22 requested changes
Left some minor comments.

2024-03-15 10:06 UTC, askayastha22 approved these changes

2024-03-15 14:23 UTC, merged