refactor: capture network error + response time RUM data
adobe/aem-genai-assistant pull request #243
Opened 2024-04-22 20:23 UTC by audrey-kho

## Description

For each generate request, we will capture additional RUM data for:
- network errors
- response time

## Related Issue

 
https://jira.corp.adobe.com/browse/SITES-21134

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-22 20:32 UTC, askayastha22 requested changes

2024-04-22 20:32 UTC, askayastha22 commented on web-src/src/components/GenerateButton.js
> +        if (error.status === 500) {
We are capturing several error codes from the backend. Can you refer to this file (https://github.com/adobe/aem-genai-assistant/blob/68f48403b7ca801ddb89444990038ecb63740efb/actions/FirefallClient.js#L26) and rewrite this logic?

2024-04-22 22:52 UTC, vtsaplin commented
Perhaps I misunderstood the request, but I assumed it should not be "RUM" but rather EIM.

2024-04-23 17:14 UTC, askayastha22 requested changes

2024-04-23 17:14 UTC, askayastha22 commented on web-src/src/components/GenerateButton.js
> +          sampleRUM('genai:prompt:generate:networkerror');
Please send the error message to RUM as well.

2024-04-23 17:50 UTC, askayastha22 approved these changes
LGTM

2024-04-23 21:16 UTC, merged