docs: additional steps in README initial setup
adobe/aem-genai-assistant pull request #251
Opened 2024-04-26 23:19 UTC by audrey-kho

## Description

Added steps that needed to be done while onboarding as a new developer

## Related Issue

 

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-04-30 19:28 UTC, askayastha22 commented
> should add directions on how to get client secret for the .env file
@audrey-kho We don't have a proper solution for this right now. Instead, can you please identify the missing required environment variables in README and add them as part of this PR?

2024-04-30 19:46 UTC, askayastha22 requested changes

2024-04-30 19:46 UTC, askayastha22 commented on README.md
> +    - `aio console workspace select`
@audrey-kho Can you investigate App Builder Quickstarts by watching this video and see if selecting org, project, and workspace can be simplified?
Link: https://www.youtube.com/live/5h5_UcxUYhU?si=7zCNq_0Rrc9IlrXw&t=1294

2024-05-01 13:56 UTC, vtsaplin approved these changes

2024-05-07 01:40 UTC, askayastha22 approved these changes

2024-05-08 20:33 UTC, askayastha22 commented
@audrey-kho Please merge this PR whenever you are ready.

2024-05-08 23:48 UTC, merged